uniqueHomePage = false

repo = "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung"


time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = true
defaultLightingMode = "dark"

codeMaxLines = 10
showLineNumbers = true

otherSearchableFields = ["Tags", "Categories", "CustomField"] # As they appear in frontmatter

enableCopyright = false

[search]
on = false
global = true # turn to `true` to enable global search
[search.algolia]
enable = false # if false search will default to fusejs
id = "Q40WQQX84U" # Application ID
index = "compose" # Index name
key = "da87401a458102ec6bbd6cc5e5cf8d95" # Search-Only API Key

[logo]
  lightMode = "images/Logo.svg"
  darkMode = "images/Logo.svg"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/Fachinformatiker-Prufungsvorbereitung/Fachinformatiker-Pruefungsvorbereitung"
